// <auto-generated />
using System;
using ForgeDB.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForgeDB.API.Data.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    [Migration("20260712184845_AddSchemaDraftWorkflow")]
    partial class AddSchemaDraftWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForgeDB.API.Models.Entities.CleaningBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CellsAffected")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("FailureDetailsJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsRestore")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUndo")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OperationCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("RowsAffected")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("cleaning_batches", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.CleaningOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CellsAffected")
                        .HasColumnType("integer");

                    b.Property<int>("CleaningBatchId")
                        .HasColumnType("integer");

                    b.Property<string>("ColumnName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsDestructive")
                        .HasColumnType("boolean");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("ResultVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("RowsAffected")
                        .HasColumnType("integer");

                    b.Property<int>("SourceVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CleaningBatchId");

                    b.HasIndex("DatasetId");

                    b.HasIndex("ResultVersionId");

                    b.HasIndex("SourceVersionId");

                    b.ToTable("cleaning_operations", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("AnalysisResultJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ColumnCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuplicateRowsCount")
                        .HasColumnType("integer");

                    b.Property<int>("MissingValuesCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActiveVersionId");

                    b.HasIndex("ProjectId");

                    b.ToTable("datasets", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DatasetColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("DetectedDataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("boolean");

                    b.Property<int>("MissingValuesCount")
                        .HasColumnType("integer");

                    b.Property<string>("SampleValues")
                        .HasColumnType("jsonb");

                    b.Property<int>("UniqueValuesCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("dataset_columns", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DatasetRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("RowData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("dataset_rows", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DatasetVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisResultJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CleaningBatchId")
                        .HasColumnType("integer");

                    b.Property<int>("ColumnCount")
                        .HasColumnType("integer");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<int>("DuplicateRowsCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRawOriginal")
                        .HasColumnType("boolean");

                    b.Property<int>("MissingValuesCount")
                        .HasColumnType("integer");

                    b.Property<string>("OperationSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<string>("RowsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CleaningBatchId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ParentVersionId");

                    b.HasIndex("DatasetId", "IsActive");

                    b.HasIndex("DatasetId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("dataset_versions", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DesignColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DesignTableId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceColumnName")
                        .HasColumnType("text");

                    b.Property<string>("SqlType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DesignTableId");

                    b.ToTable("design_columns", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DesignModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("SourceVersionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastModifiedByUserId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("design_models", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DesignRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cardinality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DesignModelId")
                        .HasColumnType("integer");

                    b.Property<int>("FromColumnId")
                        .HasColumnType("integer");

                    b.Property<string>("OnDelete")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SuggestionId")
                        .HasColumnType("integer");

                    b.Property<int>("ToColumnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DesignModelId");

                    b.HasIndex("FromColumnId");

                    b.HasIndex("SuggestionId");

                    b.HasIndex("ToColumnId");

                    b.ToTable("design_relationships", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DesignTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("DesignModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SourceDatasetId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceDatasetVersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DesignModelId");

                    b.HasIndex("SourceDatasetId");

                    b.HasIndex("SourceDatasetVersionId");

                    b.ToTable("design_tables", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DashboardConfig")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.ProjectCleaningState", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("ConfirmedVersionsJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("LastCleaningBatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastReanalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("QualityConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("QualityConfirmedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProjectId");

                    b.HasIndex("LastCleaningBatchId");

                    b.HasIndex("QualityConfirmedByUserId");

                    b.ToTable("project_cleaning_states", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.RelationshipSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceDatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetDatasetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceDatasetId");

                    b.HasIndex("TargetDatasetId");

                    b.HasIndex("ProjectId", "SourceDatasetId", "SourceColumnName", "TargetDatasetId", "TargetColumnName")
                        .IsUnique();

                    b.ToTable("relationship_suggestions", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.CleaningBatch", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.Project", "Project")
                        .WithMany("CleaningBatches")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.CleaningOperation", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.CleaningBatch", "CleaningBatch")
                        .WithMany("Operations")
                        .HasForeignKey("CleaningBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.DatasetVersion", "ResultVersion")
                        .WithMany()
                        .HasForeignKey("ResultVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ForgeDB.API.Models.Entities.DatasetVersion", "SourceVersion")
                        .WithMany()
                        .HasForeignKey("SourceVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CleaningBatch");

                    b.Navigation("Dataset");

                    b.Navigation("ResultVersion");

                    b.Navigation("SourceVersion");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.Dataset", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.DatasetVersion", "ActiveVersion")
                        .WithMany()
                        .HasForeignKey("ActiveVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ForgeDB.API.Models.Entities.Project", "Project")
                        .WithMany("Datasets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveVersion");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DatasetColumn", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.Dataset", "Dataset")
                        .WithMany("Columns")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DatasetRow", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.Dataset", "Dataset")
                        .WithMany("Rows")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DatasetVersion", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.CleaningBatch", "CleaningBatch")
                        .WithMany("ProducedVersions")
                        .HasForeignKey("CleaningBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ForgeDB.API.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.Dataset", "Dataset")
                        .WithMany("Versions")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.DatasetVersion", "ParentVersion")
                        .WithMany("ChildVersions")
                        .HasForeignKey("ParentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CleaningBatch");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Dataset");

                    b.Navigation("ParentVersion");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DesignColumn", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.DesignTable", "DesignTable")
                        .WithMany("Columns")
                        .HasForeignKey("DesignTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignTable");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DesignModel", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ForgeDB.API.Models.Entities.Project", "Project")
                        .WithOne("Design")
                        .HasForeignKey("ForgeDB.API.Models.Entities.DesignModel", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastModifiedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DesignRelationship", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.DesignModel", "DesignModel")
                        .WithMany("Relationships")
                        .HasForeignKey("DesignModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.DesignColumn", "FromColumn")
                        .WithMany()
                        .HasForeignKey("FromColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.RelationshipSuggestion", "Suggestion")
                        .WithMany("DesignRelationships")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ForgeDB.API.Models.Entities.DesignColumn", "ToColumn")
                        .WithMany()
                        .HasForeignKey("ToColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DesignModel");

                    b.Navigation("FromColumn");

                    b.Navigation("Suggestion");

                    b.Navigation("ToColumn");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DesignTable", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.DesignModel", "DesignModel")
                        .WithMany("Tables")
                        .HasForeignKey("DesignModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.Dataset", "SourceDataset")
                        .WithMany()
                        .HasForeignKey("SourceDatasetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ForgeDB.API.Models.Entities.DatasetVersion", "SourceDatasetVersion")
                        .WithMany()
                        .HasForeignKey("SourceDatasetVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DesignModel");

                    b.Navigation("SourceDataset");

                    b.Navigation("SourceDatasetVersion");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.Project", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.ProjectCleaningState", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.CleaningBatch", "LastCleaningBatch")
                        .WithMany()
                        .HasForeignKey("LastCleaningBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ForgeDB.API.Models.Entities.Project", "Project")
                        .WithOne("CleaningState")
                        .HasForeignKey("ForgeDB.API.Models.Entities.ProjectCleaningState", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.User", "QualityConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("QualityConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LastCleaningBatch");

                    b.Navigation("Project");

                    b.Navigation("QualityConfirmedByUser");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.RelationshipSuggestion", b =>
                {
                    b.HasOne("ForgeDB.API.Models.Entities.Project", "Project")
                        .WithMany("RelationshipSuggestions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.Dataset", "SourceDataset")
                        .WithMany()
                        .HasForeignKey("SourceDatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForgeDB.API.Models.Entities.Dataset", "TargetDataset")
                        .WithMany()
                        .HasForeignKey("TargetDatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("SourceDataset");

                    b.Navigation("TargetDataset");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.CleaningBatch", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("ProducedVersions");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.Dataset", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DatasetVersion", b =>
                {
                    b.Navigation("ChildVersions");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DesignModel", b =>
                {
                    b.Navigation("Relationships");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.DesignTable", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.Project", b =>
                {
                    b.Navigation("CleaningBatches");

                    b.Navigation("CleaningState");

                    b.Navigation("Datasets");

                    b.Navigation("Design");

                    b.Navigation("RelationshipSuggestions");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.RelationshipSuggestion", b =>
                {
                    b.Navigation("DesignRelationships");
                });

            modelBuilder.Entity("ForgeDB.API.Models.Entities.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
