using ForgeDB.API.Services.Generators;
using Xunit;

namespace ForgeDB.API.Tests.Generators;

public class SqlSchemaGeneratorTests
{
    [Fact]
    public void Generate_OrdersReferencesCustomers_EmitsInlineForeignKeyAndIndex()
    {
        var snapshot = Fixtures.TwoTableWithForeignKey();

        var sql = new SqlSchemaGenerator().Generate(snapshot);

        Assert.StartsWith("BEGIN;", sql);
        Assert.Contains("COMMIT;", sql);

        // Customers (the FK target) must be created before Orders in a non-cyclic graph.
        var customersIndex = sql.IndexOf("CREATE TABLE customers", StringComparison.Ordinal);
        var ordersIndex = sql.IndexOf("CREATE TABLE orders", StringComparison.Ordinal);
        Assert.True(customersIndex >= 0 && ordersIndex >= 0 && customersIndex < ordersIndex);

        Assert.Contains("PRIMARY KEY (id)", sql);
        Assert.Contains("FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE", sql);
        Assert.Contains("CREATE INDEX ix_orders_customer_id ON orders (customer_id);", sql);

        // The mixed-case/reserved-word column must be double-quoted, case preserved.
        Assert.Contains("\"Select\"", sql);
    }

    [Fact]
    public void Generate_CyclicRelationships_FallsBackToAlterTableAfterAllCreateTables()
    {
        var snapshot = Fixtures.CyclicTables();

        var sql = new SqlSchemaGenerator().Generate(snapshot);

        var lastCreateTable = sql.LastIndexOf("CREATE TABLE", StringComparison.Ordinal);
        var firstAlterTable = sql.IndexOf("ALTER TABLE", StringComparison.Ordinal);

        Assert.True(firstAlterTable > lastCreateTable, "ALTER TABLE constraints must come after every CREATE TABLE when the graph has a cycle.");
        Assert.DoesNotContain("FOREIGN KEY", sql.Substring(0, firstAlterTable));
        Assert.Contains("ADD CONSTRAINT", sql);
    }

    [Fact]
    public void Generate_TableWithComment_EmitsCommentOnTable()
    {
        var snapshot = Fixtures.TwoTableWithForeignKey();

        var sql = new SqlSchemaGenerator().Generate(snapshot);

        Assert.Contains("COMMENT ON TABLE customers IS 'Master customer list';", sql);
    }

    [Fact]
    public void Generate_ManuallyConfiguredIdentityPrimaryKey_EmitsIdentityAndPrimaryKeyWithoutRedundantUnique()
    {
        // Mirrors the exact manual configuration a user makes in Schema Design: PK + Auto Increment
        // on an integer column. IsUnique is also set here (as SaveSchemaDraftAsync always leaves it
        // for a PK column before generator-level normalization) to prove the generator itself never
        // emits a redundant UNIQUE for a PK, as defense in depth independent of the service layer.
        var snapshot = new DesignModelSnapshot
        {
            ProjectId = 1,
            ProjectName = "Demo",
            Revision = 1,
            GeneratedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
            Tables =
            [
                new DesignTableSnapshot
                {
                    Id = 1,
                    Name = "customers",
                    Columns =
                    [
                        new DesignColumnSnapshot
                        {
                            Id = 1, TableId = 1, Name = "id", SqlType = "INTEGER",
                            IsPrimaryKey = true, IsUnique = true, IsAutoIncrement = true, IsNullable = false, Ordinal = 0
                        }
                    ]
                }
            ]
        };

        var sql = new SqlSchemaGenerator().Generate(snapshot);

        Assert.Contains("id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
        Assert.Contains("PRIMARY KEY (id)", sql);
        Assert.DoesNotContain("UNIQUE", sql);
    }

    [Fact]
    public void Generate_ManuallyConfiguredUniqueNonPrimaryKeyColumn_EmitsNotNullUnique()
    {
        var snapshot = new DesignModelSnapshot
        {
            ProjectId = 1,
            ProjectName = "Demo",
            Revision = 1,
            GeneratedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
            Tables =
            [
                new DesignTableSnapshot
                {
                    Id = 1,
                    Name = "customers",
                    Columns =
                    [
                        new DesignColumnSnapshot { Id = 1, TableId = 1, Name = "id", SqlType = "INTEGER", IsPrimaryKey = true, IsNullable = false, Ordinal = 0 },
                        new DesignColumnSnapshot { Id = 2, TableId = 1, Name = "email", SqlType = "TEXT", IsUnique = true, IsNullable = false, Ordinal = 1 }
                    ]
                }
            ]
        };

        var sql = new SqlSchemaGenerator().Generate(snapshot);

        Assert.Contains("email TEXT NOT NULL UNIQUE", sql);
    }

    [Fact]
    public void Generate_ArbitraryVarcharLength_RendersExactLength()
    {
        var snapshot = new DesignModelSnapshot
        {
            ProjectId = 1,
            ProjectName = "Demo",
            Revision = 1,
            GeneratedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
            Tables =
            [
                new DesignTableSnapshot
                {
                    Id = 1,
                    Name = "customers",
                    Columns =
                    [
                        new DesignColumnSnapshot { Id = 1, TableId = 1, Name = "nickname", SqlType = "VARCHAR(100)", IsNullable = true, Ordinal = 0 }
                    ]
                }
            ]
        };

        var sql = new SqlSchemaGenerator().Generate(snapshot);

        Assert.Contains("nickname VARCHAR(100)", sql);
        Assert.DoesNotContain("VARCHAR(255)", sql);
    }
}
